GET http://localhost:7070/api/auth/test
###
POST http://localhost:7070/api/auth/register
content-type: application/json

{
    "username": "admin",
    "password": "test123"
}

###
POST http://localhost:7070/api/auth/login
content-type: application/json

{
    "username": "admin",
    "password": "test123"
}

###
GET http://localhost:7070/api/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTcyODI5NzY2OCwicm9sZXMiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbiJ9.yHmpOcP_YYo5KUOGzz3YcRwYyC5IBM62VAATexOTykc
###
GET http://localhost:7070/api/protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTcyODI5NzY2OCwicm9sZXMiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbiJ9.yHmpOcP_YYo5KUOGzz3YcRwYyC5IBM62VAATexOTykc
###
